/// @description Insert description here
// You can write your code in this editor
with game 
{
	plants_dame_level = ["None","Low","Medium","High","Very high","Apex"]
	plants_hp_level = ["Vulnerable","Low","Fairly Durable","Strong","Very Strong","Immortal"]
	plants_recharge_level = ["Extreme Slow","Slow","Little Slow","Good","Fast","Very fast","Instant"]
	plants_types = ["Sun producer","Attacker","Defender","Instant killer","Instant helper","Supporter"]
	plants_range = ["None","Close","Far","Spread","Small area","Wide area","Giant area","Whole room"]
	plants_library = [
		{
			plant_id : 1,
			plant_name : "Sun flower",
			description : "An essential plant that can't be miss in every game. She produce suns which are the fuel to born other plants\n"+
			"She likes dancing and singing like a typical cartoon flower. Every plant in the garden seems to love her. Her optimistic energy emanating from her petals making other plants boost up their spirit and fight against the monsters",
			quotation : "\"I wish the world one day is full of joy and no more sorrow\"",
			plant_food : "She obsurb the energy of the sun and produce a bunch of sun immediately",
			picture : spr_sunflower,
			card_pucture : spr_ca1,
			dame_level : plants_dame_level[0],
			hp_level : plants_hp_level[1],
			recharge_level : plants_recharge_level[4],
			card_type : obj_ca1,
			plant_types : [0],
			plants_range : [plants_range[0]],
			hp : 120,
			recharge_time : 300,
			cost : 50,
			obj_form : obj_sunflower
		},
		{
			plant_id : 2,
			plant_name : "Peashooter",
			description : "Basic attacker, shoot a bullet in a straight line at a time\n"+
			"He is not the powerful one, but he is very brave. He's willing to die for his friends and protecting the lawn",
			quotation : "\"My honor is to fight with you\"",
			plant_food : "He unlock the gatling gun ability that shoot a long stream of peas in a straight line ",
			picture : spr_peashooter,
			card_pucture : spr_ca2,
			dame_level : plants_dame_level[1],
			hp_level : plants_hp_level[1],
			recharge_level : plants_recharge_level[4],
			card_type : obj_ca2,
			plant_types : [1],
			plants_range : [plants_range[2]],
			hp : 120,
			recharge_time : 300,
			cost : 100,
			obj_form : obj_peashooter
		},
		{
			plant_id : 3,
			plant_name : "Wall nut",
			description : "Basic defender, he blocks monsters and delays them thanks to his strong health point\n"+
			"He has the \"wall \" in his name. He has known his fate. No one in this world may be able to handle this job",
			quotation : "\"Stay behind me! I'll protect you\"",
			plant_food : "He'll be equipped with an armor and double the health",
			picture : spr_wallnut2,
			card_pucture : spr_ca3,
			dame_level : plants_dame_level[0],
			hp_level : plants_hp_level[3],
			recharge_level : plants_recharge_level[1],
			card_type : obj_ca3,
			plant_types : [2],
			plants_range : [plants_range[0]],
			hp : 2000,
			recharge_time : 1500,
			cost : 50,
			obj_form : obj_wallnut
		},
		{
			plant_id : 4,
			plant_name : "Potato mine",
			description : "Take a time to charge. After that, anyone who touch him will be shut down\n"+
			"It might seems psychotic but he'll be very happy to have a feet of a monster step on and then ends both lifes",
			quotation : "\"Closer... Closer... That right!\"",
			plant_food : "He'll throws other 2 clones into random positions. They're immediately charged",
			picture : spr_potatomine,
			card_pucture : spr_ca4,
			dame_level : plants_dame_level[4],
			hp_level : plants_hp_level[1],
			recharge_level : plants_recharge_level[1],
			card_type : obj_ca4,
			plant_types : [3],
			plants_range : [plants_range[4]],
			hp : 100,
			recharge_time : 1500,
			cost : 25,
			obj_form : obj_potatobom
		},
		{
			plant_id : 5,
			plant_name : "Repeater",
			description : "An upgraded peashooter that'll shoot 2 peas in a straight line at a time\n"+
			"If a peashooter lives long enough, he'll become senior peashooter, or we may informally call Repeaters",
			quotation : "\"Bring your asses in! I'll slay all in one shot!\"",
			plant_food : "He got the same effect as peashooter but double the amount of peas",
			picture : spr_repeater,
			card_pucture : spr_ca5,
			dame_level : plants_dame_level[2],
			hp_level : plants_hp_level[1],
			recharge_level : plants_recharge_level[4],
			card_type : obj_ca5,
			plant_types : [1],
			plants_range : [plants_range[2]],
			hp : 120,
			recharge_time : 300,
			cost : 200,
			obj_form : obj_repeater
		},
		{
			plant_id : 6,
			plant_name : "Snow pea",
			description : "Shoot an icy pea that slows down the monsters\n"+
			"The origin of snow pea is still in debate. One of them said that they're regular peashooters who has been enchanted by Ice God (Chai) and inherit the ice power",
			quotation : "\"Don't need to rush. Just chill!\"",
			plant_food : "He blows an ice cloud that freezes all the monster on the way. Then he finishs them by a stream of peas just like peashooters",
			picture : spt_snowpea,
			card_pucture : spr_ca6,
			dame_level : plants_dame_level[1],
			hp_level : plants_hp_level[1],
			recharge_level : plants_recharge_level[4],
			card_type : obj_ca6,
			plant_types : [1,5],
			plants_range : [plants_range[2]],
			hp : 120,
			recharge_time : 300,
			cost : 175,
			obj_form : obj_icepea
		},
		{
			plant_id : 7,
			plant_name : "Cherry bomb",
			description : "Explode an 3x3 area and instantly kills all the monsters surrounding\n"+
			"This dangerous weapon is so hard to preserved. They're so easy to get excited and them BOOM. Don't get too close to them when this happens",
			quotation : "\"WE CAN'T TALK IN LOWERCASE AND WITHOUT AN EXCLAMATION POINT!\"",
			plant_food : "*Mystery*",
			picture : spr_cherrybom,
			card_pucture : spr_ca7,
			dame_level : plants_dame_level[4],
			hp_level : plants_hp_level[5],
			recharge_level : plants_recharge_level[1],
			card_type : obj_ca7,
			plant_types : [3],
			plants_range : [plants_range[5]],
			hp : 10000,
			recharge_time : 1500,
			cost : 150,
			obj_form : obj_cherrybom
		},
		{
			plant_id : 8,
			plant_name : "Castus",
			description : "The first monopoly plant. He is multifunctional, attacks like a normal peashooter while the monsters are far away and switches to melee attack when they are close\n" +
			"Wall-nuts may get jealous of him because he can be the second defense plant. The pea family also doesn't like him so much since he could also attack just like them. He is the type of nerd in a class that answers all of the teacher questions and gets admired or jealous of other students",
			quotation : "\"You shall NOT PASS!!\"",
			plant_food : "Get an upgrade with blue thorns and deal x3 damage, lasts forever",
			picture : spr_castuss,
			card_pucture : spr_ca8,
			dame_level : plants_dame_level[2],
			hp_level : plants_hp_level[2],
			recharge_level : plants_recharge_level[3],
			card_type : obj_ca8,
			plant_types : [1,2],
			plants_range : [plants_range[2],plants_range[4]],
			hp : 500,
			recharge_time : 420,
			cost : 175,
			obj_form : obj_castuss
		},
		{
			plant_id : 9,
			plant_name : "Icelettuce",
			description : "Freeze the monster if they attack this plant\n"+
			"He is so small but yet so dangerous. You would feel a temperature of 10 degree C when standing arround him. Touch him slightly would cause you a frostbite",
			quotation : "\"What is colder? The endless flow of winter winds or human's heart?\"",
			plant_food : "Release an ice shockwave that freezes all the enemies visible in the room",
			picture : spr_icelettuce,
			card_pucture : spr_ca9,
			dame_level : plants_dame_level[0],
			hp_level : plants_hp_level[1],
			recharge_level : plants_recharge_level[2],
			card_type : obj_ca9,
			plant_types : [4],
			plants_range : [plants_range[4]],
			hp : 100,
			recharge_time : 1200,
			cost : 0,
			obj_form : obj_iceletuce
		},
		{
			plant_id : 10,
			plant_name : "Squash",
			description : "When monsters get close enough, he jumps on them and presses them to death\n"+
			"No one can ever measure the exact weight of him and he never please to let someone do that. All we know that if he jumps and then lands, a 5 degree Richter earthquake would happens ",
			quotation : "\"So you have choosen... death!\"",
			plant_food : "Jump extremely high and then land on the nearest monsters. The impact create an explosion similar to cherry bomb's one and kills all surrounding monsters",
			picture : spr_squash,
			card_pucture : spr_ca10,
			dame_level : plants_dame_level[4],
			hp_level : plants_hp_level[1],
			recharge_level : plants_recharge_level[1],
			card_type : obj_ca10,
			plant_types : [3],
			plants_range : [plants_range[4]],
			hp : 120,
			recharge_time : 1500,
			cost : 50,
			obj_form : obj_squash
		},
		{
			plant_id : 11,
			plant_name : "Split Pea",
			description : "Shoot both direction, one in the front and two in the back\n"+
			"This weird specie of pea may came from the failed hybrid of peashooter and repeater. Better off don't think about it. Atleast, he (or they) will never be afraid of loneliness",
			quotation : "\"Have you ever wonder how can we expel excess substances?\".\"WE DON'T ALBERT!!!!\"",
			plant_food : "Combination of peashooter and repeater, but with two different directions",
			picture : spr_splitpea,
			card_pucture : spr_ca11,
			dame_level : plants_dame_level[1],
			hp_level : plants_hp_level[1],
			recharge_level : plants_recharge_level[4],
			card_type : obj_ca11,
			plant_types : [1],
			plants_range : [plants_range[2]],
			hp : 120,
			recharge_time : 300,
			cost : 125,
			obj_form : obj_splitpea
		},
		{
			plant_id : 12,
			plant_name : "Dragonfruit",
			description : "Spit fire and deal piercing damage. Very helpful when dealing with large amount of enemies\n"+
			"Dragonfruit is now can lives exactly like what his name indicates. He or his specie is the descendants of the Dragon",
			quotation : "\"Flames ain't natural!\"",
			plant_food : "Summon a big fire tornado that wipe out 3 lanes straight!",
			picture : spr_dragonfruit,
			card_pucture : spr_ca12,
			dame_level : plants_dame_level[2],
			hp_level : plants_hp_level[1],
			recharge_level : plants_recharge_level[4],
			card_type : obj_ca12,
			plant_types : [1],
			plants_range : [plants_range[1]],
			hp : 120,
			recharge_time : 300,
			cost : 150,
			obj_form : obj_dragonfruit
		},
		{
			plant_id : 13,
			plant_name : "Eggplant",
			description : "Ram into the monsters and make them out of their lane\n"+
			"Eggplant full evolution would have 4 matches as his legs. This make them look like a rhinoceros than an eggplant. This is too scary so the Garden Owner has removed the matches!",
			quotation : "\"DON'T CALL ME EGGG!!!\"",
			plant_food : "Making a charge and gore all the monsters on the lane to a different dimension",
			picture : spr_eggplant,
			card_pucture : spr_ca13,
			dame_level : plants_dame_level[1],
			hp_level : plants_hp_level[1],
			recharge_level : plants_recharge_level[2],
			card_type : obj_ca13,
			plant_types : [4,5],
			plants_range : [plants_range[1]],
			hp : 120,
			recharge_time : 750,
			cost : 50,
			obj_form : obj_eggplant
		},
		{
			plant_id : 14,
			plant_name : "Lily pad",
			description : "She will help you to hold your plants on the water\n"+
			"If you have a bad day, just think about lily pad. She can't do nothing other than support her friends to fight against the monsters. She takes a minimum credit however, she's still willing to do that",
			quotation : "\"I'm fine.\"",
			plant_food : "Clones 4 version of herself into nearest water ponds",
			picture : spr_lilypad,
			card_pucture : spr_ca14,
			dame_level : plants_dame_level[0],
			hp_level : plants_hp_level[1],
			recharge_level : plants_recharge_level[3],
			card_type : obj_ca14,
			plant_types : [5],
			plants_range : [plants_range[0]],
			hp : 120,
			recharge_time : 450,
			cost : 25,
			obj_form : obj_lilypad
		},
		{
			plant_id : 15,
			plant_name : "Threepeater",
			description : "Shoot 3 peas in in his lane and other 2 adjacent lanes\n"+
			"Threepeater hold a very high standard in the pea family. A peashooter want to become threepeater, he has to practice for 9 lifetimes. All three heads of the threepeater usually share the same thought!",
			quotation : "\"We bare peas\"",
			plant_food : "The same as other peas but along with a storms of peas, they spread everywhere on the room",
			picture : spr_threepeater,
			card_pucture : spr_ca15,
			dame_level : plants_dame_level[1],
			hp_level : plants_hp_level[1],
			recharge_level : plants_recharge_level[4],
			card_type : obj_ca15,
			plant_types : [1],
			plants_range : [plants_range[2],plants_range[3]],
			hp : 120,
			recharge_time : 300,
			cost : 325,
			obj_form : obj_threepeater
		},
		{
			plant_id : 16,
			plant_name : "Blover",
			description : "Blow away floating monsters\n"+
			"Her propeller is very hard and strong. The wind created when her's swinging can reach up to 200 km/h. Enough to push mid air enemies to the realm of ecstasy",
			quotation : "\"Get out of my lawn!!\"",
			plant_food : "*Mystery*",
			picture : spr_blover,
			card_pucture : spr_ca16,
			dame_level : plants_dame_level[0],
			hp_level : plants_hp_level[5],
			recharge_level : plants_recharge_level[3],
			card_type : obj_ca16,
			plant_types : [4],
			plants_range : [plants_range[7]],
			hp : 10000,
			recharge_time : 600,
			cost : 50,
			obj_form : obj_blover
		},
		{
			plant_id : 17,
			plant_name : "Chomper",
			description : "Wait for bad luck monsters to step in and become her sweat meal\n"+
			"This species of carnivorous plant would like lying down instead of standing up. Her pistil emits a lot of fragrance. Not only monsters, every single living thing will try to approach her and end up badly.",
			quotation : "\"Hello, I've been waiting here since afternoon\"",
			plant_food : "Summons other chompers from the ground. Consume some of the monsters and then disappear",
			picture : spr_chomper,
			card_pucture : spr_ca17,
			dame_level : plants_dame_level[4],
			hp_level : plants_hp_level[2],
			recharge_level : plants_recharge_level[4],
			card_type : obj_ca17,
			plant_types : [2,4],
			plants_range : [plants_range[4]],
			hp : 500,
			recharge_time : 450,
			cost : 175,
			obj_form : obj_chomper
		},
		{
			plant_id : 18,
			plant_name : "Banana Heart",
			description : "Shoot a banana heart missile toward and enemies in front and then blow up deals sweeping damage\n"+
			"Banana Heart is a professional catapult. His banana heart contains nothing but gun powder. He has OCD and very afraid of missing",
			quotation : "\"I've practiced this shot for thousand times\"",
			plant_food : "His banana heart blooms and release a rain of banana bomb. Deals heavy dame to the enemy ranks",
			picture : spr_bananaheart,
			card_pucture : spr_ca18,
			dame_level : plants_dame_level[3],
			hp_level : plants_hp_level[1],
			recharge_level : plants_recharge_level[4],
			card_type : obj_ca18,
			plant_types : [1],
			plants_range : [plants_range[2]],
			hp : 120,
			recharge_time : 300,
			cost : 350,
			obj_form : obj_bananaheart
		},
		{
			plant_id : 19,
			plant_name : "Custarnade",
			description : "Works like a real gernade. Blows up and shoot his fragments everywhere\n"+
			"Once the safety pin is pulled out, no matter how far you run. You would probably if not dead then must be seriously injured. He actually adore Cherry bomb and afraid of Doom shroom",
			quotation : "\"Where can you run to avoid the sun?\"",
			plant_food : "*Mystery*",
			picture : spr_custarnade,
			card_pucture : spr_ca19,
			dame_level : plants_dame_level[3],
			hp_level : plants_hp_level[5],
			recharge_level : plants_recharge_level[1],
			card_type : obj_ca19,
			plant_types : [3],
			plants_range : [plants_range[7]],
			hp : 10000,
			recharge_time : 1200,
			cost : 100,
			obj_form : obj_custarnade
		},
		{
			plant_id : 20,
			plant_name : "Puff-shroom",
			description : "Act as a short range peashooter and may be a staller\n"+
			"He and his specie must be the smallest plant in this game. Don't be fooled by his look, he is super powerful when the night falls. Every plant laughing at him but little did they know, without him, they hardly be born with out the natural sunlight",
			quotation : "\"A small shroom has a big dream, to change to world using his smallest action\"",
			plant_food : "Shoot a stream of spores, same as peashooter but half the range",
			picture : spr_puffshroom,
			card_pucture : spr_ca20,
			dame_level : plants_dame_level[1],
			hp_level : plants_hp_level[0],
			recharge_level : plants_recharge_level[4],
			card_type : obj_ca20,
			plant_types : [1],
			plants_range : [plants_range[1]],
			hp : 80,
			recharge_time : 360,
			cost : 0,
			obj_form : obj_puffshroom
		},
		{
			plant_id : 21,
			plant_name : "Sunshroom",
			description : "A night version sun producer. Start with small sun and then grow up and produce sun like a regular sun flower \n"+
			"Sunflower must be happy since her counterpart finally show up to share her burden. How can sun shroom produce sun in the darkness? Umm.. this book is not a science book",
			quotation : "\"My childhood just last for few minutes\"",
			plant_food : "Instantly grow up, and produce serveral giant suns",
			picture : spr_sunshroom,
			card_pucture : spr_ca21,
			dame_level : plants_dame_level[0],
			hp_level : plants_hp_level[1],
			recharge_level : plants_recharge_level[4],
			card_type : obj_ca21,
			plant_types : [0],
			plants_range : [plants_range[0]],
			hp : 120,
			recharge_time : 300,
			cost : 25,
			obj_form : obj_sunshroom
		},
		{
			plant_id : 22,
			plant_name : "Blasting Lotus",
			description : "Destroys the annoying crystals\n"+
			"She doesn't choose to grow on soil like others, but a hard, inorganic materials like the crystals. Because she know that is her duty, she know that she has ability to destroy them. If she doesn't, no one can push back those crystals!",
			quotation : "\"Try to live like a flower growing in the middle of a barren desert\"",
			plant_food : "*Mystery*",
			picture : spr_blasterflower,
			card_pucture : spr_ca22,
			dame_level : plants_dame_level[1],
			hp_level : plants_hp_level[1],
			recharge_level : plants_recharge_level[2],
			card_type : obj_ca22,
			plant_types : [4],
			plants_range : [plants_range[5]],
			hp : 120,
			recharge_time : 450,
			cost : 25,
			obj_form : obj_blasterflower
		},
		{
			plant_id : 23,
			plant_name : "Photonenopsis",
			description : "Shoot a light beam. Can manually adjust her direction by scrolling mouse. The light can be reflected by the crystal\n"+
			"Her name is the combination of 'Photon' (particle of light) and 'Phalaenopsis'. She is powerful but not so good at calculating. That's why she need your helpe of redirecting her aim",
			quotation : "\"Hmm.. trying to figure out how to make my light go through all monsters in one shot!\"",
			plant_food : "The beam becomes more deadly and moves up and down, wipes out all monsters in the front",
			picture : spr_lightflower,
			card_pucture : spr_ca23,
			dame_level : plants_dame_level[3],
			hp_level : plants_hp_level[1],
			recharge_level : plants_recharge_level[4],
			card_type : obj_ca23,
			plant_types : [1],
			plants_range : [plants_range[6]],
			hp : 120,
			recharge_time : 300,
			cost : 300,
			obj_form : obj_lightflower
		},
		{
			plant_id : 24,
			plant_name : "Sadshroom",
			description : "Shoot a infectous spore at a random monsters in the front. If this spore kill them, they will become a random murshroom\n"+
			"Why he is called 'Sadshroom'? He is not sad, but his unchangeable face makes him look like that. You can call him FOAS (Father of all Shrooms) since he can give birth to any of his other Shroom counterparts.",
			quotation : "\"Change into Doom shroom please!\"",
			plant_food : "Shoot mulitples infectous spores and deals heavy damage. Increase the chance of monsters getting killed by those and spawning a new shroom",
			picture : spr_sadshroom,
			card_pucture : spr_ca24,
			dame_level : plants_dame_level[1],
			hp_level : plants_hp_level[1],
			recharge_level : plants_recharge_level[4],
			card_type : obj_ca24,
			plant_types : [1],
			plants_range : [plants_range[6]],
			hp : 120,
			recharge_time : 300,
			cost : 150,
			obj_form : obj_sadshroom
		},
		{
			plant_id : 25,
			plant_name : "Poison shroom",
			description : "Fire a poisonous spore at the enemies which will blows up and infect surrounding with posion\n"+
			"Other plants call him a Toxic shroom. As the name suggest, he's actually toxic. The poison from his bullet or the toxins from his words can both deal heavy damage and finish you",
			quotation : "\"There are two types of failures, one is always making people pleased, and the other type is reading this line\"",
			plant_food : "Summon a dark purple cloud than full of poison, it'll will slowly move forward and make the monsters die painfully while getting poisoned",
			picture : spr_poisonshroom,
			card_pucture : spr_ca25,
			dame_level : plants_dame_level[2],
			hp_level : plants_hp_level[1],
			recharge_level : plants_recharge_level[4],
			card_type : obj_ca25,
			plant_types : [1],
			plants_range : [plants_range[2],plants_range[3]],
			hp : 120,
			recharge_time : 300,
			cost : 225,
			obj_form : obj_possonshroom
		},
		{
			plant_id : 100,
			plant_name : "Doom shroom",
			description : "Creates a horrific explosion in nearly full room and leaves a crater\n"+
			"This black thing is scared by both plants and monsters. The explosion created is the equivalent of the Hiroshima explosion. Storing these plants in your house isn't different much from storing nuclear weapons",
			quotation : "\"A few people laughed, few people cried, but most people were silent\"",
			plant_food : "*This thing is already too powerful for the plant food*",
			picture : spr_doomshroom,
			card_pucture : spr_ca0,
			dame_level : plants_dame_level[4],
			hp_level : plants_hp_level[5],
			recharge_level : plants_recharge_level[0],
			card_type : obj_ca0,
			plant_types : [3],
			plants_range : [plants_range[6]],
			hp : 10000,
			recharge_time : 2000,
			cost : 200,
			obj_form : obj_doomshroom
		},
	]	
}





