function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 300; // obj_tiles
	global.__objectDepths[1] = 500; // obj_endangered
	global.__objectDepths[2] = 500; // obj_crystal
	global.__objectDepths[3] = 400; // obj_waterlogged
	global.__objectDepths[4] = 0; // obj_wavy
	global.__objectDepths[5] = 500; // obj_muddy
	global.__objectDepths[6] = 0; // obj_cursedstatue
	global.__objectDepths[7] = 0; // obj_parent_mons
	global.__objectDepths[8] = -50; // obj_seedy
	global.__objectDepths[9] = 0; // obj_parent_plant
	global.__objectDepths[10] = 0; // obj_projectile
	global.__objectDepths[11] = 0; // obj_otherdame
	global.__objectDepths[12] = 0; // obj_treeOfWishom
	global.__objectDepths[13] = 0; // obj_sunflower
	global.__objectDepths[14] = 0; // obj_peashooter
	global.__objectDepths[15] = 0; // obj_icepea
	global.__objectDepths[16] = 0; // obj_repeater
	global.__objectDepths[17] = 0; // obj_wallnut
	global.__objectDepths[18] = 0; // obj_potatobom
	global.__objectDepths[19] = 0; // obj_cherrybom
	global.__objectDepths[20] = 0; // obj_castuss
	global.__objectDepths[21] = 0; // obj_iceletuce
	global.__objectDepths[22] = 0; // obj_squash
	global.__objectDepths[23] = 0; // obj_splitpea
	global.__objectDepths[24] = 0; // obj_dragonfruit
	global.__objectDepths[25] = 0; // obj_eggplant
	global.__objectDepths[26] = 0; // obj_lilypad
	global.__objectDepths[27] = 0; // obj_threepeater
	global.__objectDepths[28] = 0; // obj_blover
	global.__objectDepths[29] = 0; // obj_chomper
	global.__objectDepths[30] = 0; // obj_bananaheart
	global.__objectDepths[31] = 0; // obj_custarnade
	global.__objectDepths[32] = 0; // obj_puffshroom
	global.__objectDepths[33] = 0; // obj_sunshroom
	global.__objectDepths[34] = 0; // obj_blasterflower
	global.__objectDepths[35] = 0; // obj_lightflower
	global.__objectDepths[36] = 0; // obj_sadshroom
	global.__objectDepths[37] = 0; // obj_possonshroom
	global.__objectDepths[38] = 0; // obj_doomshroom
	global.__objectDepths[39] = 0; // obj_ca0
	global.__objectDepths[40] = -50; // obj_ca1
	global.__objectDepths[41] = -50; // obj_ca2
	global.__objectDepths[42] = -50; // obj_ca3
	global.__objectDepths[43] = -50; // obj_ca4
	global.__objectDepths[44] = -50; // obj_ca5
	global.__objectDepths[45] = -50; // obj_ca6
	global.__objectDepths[46] = -50; // obj_ca7
	global.__objectDepths[47] = -50; // obj_ca8
	global.__objectDepths[48] = -50; // obj_ca9
	global.__objectDepths[49] = -50; // obj_ca10
	global.__objectDepths[50] = -50; // obj_ca11
	global.__objectDepths[51] = -50; // obj_ca12
	global.__objectDepths[52] = -50; // obj_ca13
	global.__objectDepths[53] = -50; // obj_ca14
	global.__objectDepths[54] = -50; // obj_ca15
	global.__objectDepths[55] = -50; // obj_ca16
	global.__objectDepths[56] = -50; // obj_ca17
	global.__objectDepths[57] = -50; // obj_ca18
	global.__objectDepths[58] = -50; // obj_ca19
	global.__objectDepths[59] = -50; // obj_ca20
	global.__objectDepths[60] = -50; // obj_ca21
	global.__objectDepths[61] = -50; // obj_ca22
	global.__objectDepths[62] = -50; // obj_ca23
	global.__objectDepths[63] = -50; // obj_ca24
	global.__objectDepths[64] = -50; // obj_ca25
	global.__objectDepths[65] = 0; // obj_cshovel
	global.__objectDepths[66] = -100; // obj_cpf
	global.__objectDepths[67] = 0; // obj_monster
	global.__objectDepths[68] = 0; // obj_brownie
	global.__objectDepths[69] = 0; // obj_monsterdog
	global.__objectDepths[70] = 0; // obj_hardcore
	global.__objectDepths[71] = 0; // obj_imp
	global.__objectDepths[72] = 0; // obj_gigantic
	global.__objectDepths[73] = 0; // obj_blackdog
	global.__objectDepths[74] = 0; // obj_scorpion
	global.__objectDepths[75] = 0; // obj_sandstorm
	global.__objectDepths[76] = 0; // obj_driller
	global.__objectDepths[77] = 0; // obj_rex
	global.__objectDepths[78] = 0; // obj_scopiking
	global.__objectDepths[79] = 0; // obj_desertSummoner
	global.__objectDepths[80] = 0; // obj_dragonfly
	global.__objectDepths[81] = 0; // obj_krockodile
	global.__objectDepths[82] = 0; // obj_spider
	global.__objectDepths[83] = 0; // obj_slime
	global.__objectDepths[84] = 0; // obj_urusal
	global.__objectDepths[85] = 0; // obj_swampSummer
	global.__objectDepths[86] = 0; // obj_skelegon
	global.__objectDepths[87] = 0; // obj_crystard
	global.__objectDepths[88] = 0; // obj_eyebat
	global.__objectDepths[89] = 0; // obj_helahula
	global.__objectDepths[90] = 0; // obj_darkpatrol
	global.__objectDepths[91] = 0; // obj_annabelle
	global.__objectDepths[92] = 0; // obj_vollo
	global.__objectDepths[93] = 0; // obj_crylandsummoner
	global.__objectDepths[94] = -10; // obj_piercing
	global.__objectDepths[95] = -25; // obj_plantfood
	global.__objectDepths[96] = -25; // obj_sunny
	global.__objectDepths[97] = 1; // obj_snowpea
	global.__objectDepths[98] = 1; // obj_pea
	global.__objectDepths[99] = 0; // obj_potatoboms
	global.__objectDepths[100] = 0; // obj_impact
	global.__objectDepths[101] = 0; // obj_bucxanhiet
	global.__objectDepths[102] = 0; // obj_waving
	global.__objectDepths[103] = 0; // obj_bucxanhiet2
	global.__objectDepths[104] = -100; // obj_flash
	global.__objectDepths[105] = -100; // obj_flash2
	global.__objectDepths[106] = 0; // obj_shutdown
	global.__objectDepths[107] = 1; // obj_skmna
	global.__objectDepths[108] = 1; // obj_poisonous
	global.__objectDepths[109] = 0; // obj_lawnmover
	global.__objectDepths[110] = -10; // obj_venomshoot
	global.__objectDepths[111] = 0; // obj_floorfire
	global.__objectDepths[112] = -50; // obj_spiderweb
	global.__objectDepths[113] = 0; // obj_bananabomb
	global.__objectDepths[114] = 0; // obj_spore
	global.__objectDepths[115] = -100; // obj_tounge
	global.__objectDepths[116] = 0; // obj_poisonbomb
	global.__objectDepths[117] = 0; // obj_diemkydi
	global.__objectDepths[118] = -25; // obj_crystalbroke
	global.__objectDepths[119] = 0; // obj_laserbeam
	global.__objectDepths[120] = 0; // obj_pseudolight
	global.__objectDepths[121] = 0; // obj_mysteriouswave
	global.__objectDepths[122] = 0; // obj_possonspread
	global.__objectDepths[123] = 1; // obj_possonblt
	global.__objectDepths[124] = 0; // obj_possoncloud
	global.__objectDepths[125] = 0; // obj_sporedest
	global.__objectDepths[126] = 0; // obj_phonglon
	global.__objectDepths[127] = 0; // obj_fireskull
	global.__objectDepths[128] = 100; // obj_vtmp
	global.__objectDepths[129] = -100; // obj_light
	global.__objectDepths[130] = -300; // obj_smassh
	global.__objectDepths[131] = -100; // director
	global.__objectDepths[132] = 0; // obj_sunpoint
	global.__objectDepths[133] = -333; // obj_hugewave
	global.__objectDepths[134] = -333; // obj_finalwave
	global.__objectDepths[135] = -333; // obj_pLants
	global.__objectDepths[136] = -1000; // obj_yoilost
	global.__objectDepths[137] = 0; // obj_poisonexp
	global.__objectDepths[138] = -5; // obj_greenTargeted
	global.__objectDepths[139] = -5; // obj_purpleTargeted
	global.__objectDepths[140] = -30; // obj_abouttoshoot
	global.__objectDepths[141] = -5; // obj_poisonlaser
	global.__objectDepths[142] = -250; // obj_lvlup
	global.__objectDepths[143] = -140; // obj_apple
	global.__objectDepths[144] = 0; // obj_bananadest
	global.__objectDepths[145] = 0; // obj_gernadecap
	global.__objectDepths[146] = 100; // obj_wormhair
	global.__objectDepths[147] = -10; // obj_4by4des
	global.__objectDepths[148] = -250; // obj_poisonbam
	global.__objectDepths[149] = -250; // obj_muddyblast
	global.__objectDepths[150] = 0; // obj_urusalhead
	global.__objectDepths[151] = 0; // obj_skelegonCorpse
	global.__objectDepths[152] = 0; // obj_annabelleCorpse
	global.__objectDepths[153] = 0; // obj_centrelight
	global.__objectDepths[154] = 0; // obj_lightpillar
	global.__objectDepths[155] = -250; // obj_bamsummon
	global.__objectDepths[156] = -250; // obj_fsexp
	global.__objectDepths[157] = 0; // obj_boxmodel
	global.__objectDepths[158] = 0; // obj_touchpoint
	global.__objectDepths[159] = -100; // obj_lightlaunch
	global.__objectDepths[160] = 0; // obj_lightdirect
	global.__objectDepths[161] = -30; // obj_banbeam
	global.__objectDepths[162] = 0; // obj_hiroshima
	global.__objectDepths[163] = 0; // obj_crater
	global.__objectDepths[164] = 0; // obj_soul
	global.__objectDepths[165] = -300; // obj_vollohead
	global.__objectDepths[166] = 0; // obj_hometown
	global.__objectDepths[167] = 0; // obj_desert
	global.__objectDepths[168] = 0; // obj_swamp
	global.__objectDepths[169] = 0; // obj_cryland
	global.__objectDepths[170] = 0; // obj_kangdynasty
	global.__objectDepths[171] = 0; // obj_volcanic
	global.__objectDepths[172] = 0; // obj_arenaofvalor
	global.__objectDepths[173] = -60; // obj_letrock
	global.__objectDepths[174] = 0; // obj_letrock2
	global.__objectDepths[175] = 0; // obj_return
	global.__objectDepths[176] = 0; // obj_getgo
	global.__objectDepths[177] = 0; // obj_unlock
	global.__objectDepths[178] = -100; // obj_drop1
	global.__objectDepths[179] = -100; // obj_drop2
	global.__objectDepths[180] = -100; // obj_drop3
	global.__objectDepths[181] = -10; // obj_arrow
	global.__objectDepths[182] = 0; // bufferer
	global.__objectDepths[183] = -10; // levelsystem1
	global.__objectDepths[184] = -200; // controller
	global.__objectDepths[185] = 50; // obj_plantboard
	global.__objectDepths[186] = -45; // obj_selectboard
	global.__objectDepths[187] = 50; // obj_voyager
	global.__objectDepths[188] = 0; // obj_line1
	global.__objectDepths[189] = 0; // obj_line2
	global.__objectDepths[190] = 0; // obj_line3
	global.__objectDepths[191] = 0; // obj_line4
	global.__objectDepths[192] = 0; // obj_line5
	global.__objectDepths[193] = -999; // obj_white
	global.__objectDepths[194] = -999; // obj_black
	global.__objectDepths[195] = 0; // obj_spectator
	global.__objectDepths[196] = 0; // obj_enemies
	global.__objectDepths[197] = 5; // obj_PR
	global.__objectDepths[198] = 0; // obj_lvl1_b
	global.__objectDepths[199] = 0; // obj_lvl2_b
	global.__objectDepths[200] = 0; // obj_lvl3_b
	global.__objectDepths[201] = 0; // obj_lvl4_b
	global.__objectDepths[202] = 0; // obj_lvl5_b
	global.__objectDepths[203] = 0; // obj_lvl6_b
	global.__objectDepths[204] = 0; // obj_lvl7_b
	global.__objectDepths[205] = 0; // obj_lvl8_b
	global.__objectDepths[206] = 0; // obj_lvl9_b
	global.__objectDepths[207] = 0; // obj_lvl10_b
	global.__objectDepths[208] = 0; // obj_lvl1_c
	global.__objectDepths[209] = 0; // obj_lvl2_c
	global.__objectDepths[210] = 0; // obj_lvl3_c
	global.__objectDepths[211] = 0; // obj_lvl4_c
	global.__objectDepths[212] = 0; // obj_lvl5_c
	global.__objectDepths[213] = 0; // obj_lvl6_c
	global.__objectDepths[214] = 0; // obj_lvl7_c
	global.__objectDepths[215] = 0; // obj_lvl8_c
	global.__objectDepths[216] = 0; // obj_lvl9_c
	global.__objectDepths[217] = 0; // obj_lvl10_c
	global.__objectDepths[218] = 0; // obj_lvl11_c
	global.__objectDepths[219] = 0; // obj_lvl12_c
	global.__objectDepths[220] = 0; // obj_lvl13_c
	global.__objectDepths[221] = 0; // obj_lvl1_d
	global.__objectDepths[222] = 0; // obj_lvl2_d
	global.__objectDepths[223] = 0; // obj_lvl3_d
	global.__objectDepths[224] = 0; // obj_lvl4_d
	global.__objectDepths[225] = 0; // obj_lvl5_d
	global.__objectDepths[226] = 0; // obj_lvl6_d
	global.__objectDepths[227] = 0; // obj_lvl7_d
	global.__objectDepths[228] = 0; // obj_lvl8_d
	global.__objectDepths[229] = 0; // obj_lvl9_d
	global.__objectDepths[230] = 0; // obj_lvl10_d
	global.__objectDepths[231] = 0; // obj_lvl11_d
	global.__objectDepths[232] = 0; // obj_lvl12_d
	global.__objectDepths[233] = 0; // obj_lvl1_e
	global.__objectDepths[234] = 0; // obj_lvl2_e
	global.__objectDepths[235] = 0; // obj_lvl3_e
	global.__objectDepths[236] = 0; // obj_lvl4_e
	global.__objectDepths[237] = 0; // obj_lvl5_e
	global.__objectDepths[238] = 0; // obj_lvl6_e
	global.__objectDepths[239] = 0; // obj_lvl7_e
	global.__objectDepths[240] = 0; // obj_lvl8_e
	global.__objectDepths[241] = 0; // obj_lvl9_e
	global.__objectDepths[242] = 0; // obj_lvl10_e
	global.__objectDepths[243] = 0; // obj_lvl11_e
	global.__objectDepths[244] = 0; // obj_lvl12_e
	global.__objectDepths[245] = 0; // obj_lvl13_e
	global.__objectDepths[246] = 0; // obj_lvl14_e
	global.__objectDepths[247] = -19; // lvl1_hometown
	global.__objectDepths[248] = -19; // lvl2_hometown
	global.__objectDepths[249] = -19; // lvl3_hometown
	global.__objectDepths[250] = -19; // lvl4_hometown
	global.__objectDepths[251] = -19; // lvl5_hometown
	global.__objectDepths[252] = -19; // lvl6_hometown
	global.__objectDepths[253] = -19; // lvl7_hometown
	global.__objectDepths[254] = -19; // lvl8_hometown
	global.__objectDepths[255] = -19; // lvl9_hometown
	global.__objectDepths[256] = -19; // lvl10_hometown
	global.__objectDepths[257] = -19; // lvl1_desert
	global.__objectDepths[258] = -19; // lvl2_desert
	global.__objectDepths[259] = -19; // lvl3_desert
	global.__objectDepths[260] = -19; // lvl4_desert
	global.__objectDepths[261] = -19; // lvl5_desert
	global.__objectDepths[262] = -19; // lvl6_desert
	global.__objectDepths[263] = -19; // lvl7_desert
	global.__objectDepths[264] = -19; // lvl8_desert
	global.__objectDepths[265] = -19; // lvl9_desert
	global.__objectDepths[266] = -19; // lvl10_desert
	global.__objectDepths[267] = -19; // lvl11_desert
	global.__objectDepths[268] = -19; // lvl12_desert
	global.__objectDepths[269] = -19; // lvl13_desert
	global.__objectDepths[270] = -19; // lvl1_swamp
	global.__objectDepths[271] = -19; // lvl2_swamp
	global.__objectDepths[272] = -19; // lvl3_swamp
	global.__objectDepths[273] = -201; // lvl4_swamp
	global.__objectDepths[274] = -19; // lvl5_swamp
	global.__objectDepths[275] = -19; // lvl6_swamp
	global.__objectDepths[276] = -19; // lvl7_swamp
	global.__objectDepths[277] = -19; // lvl8_swamp
	global.__objectDepths[278] = -19; // lvl9_swamp
	global.__objectDepths[279] = -19; // lvl10_swamp
	global.__objectDepths[280] = -19; // lvl11_swamp
	global.__objectDepths[281] = -19; // lvl12_swamp
	global.__objectDepths[282] = -19; // lvl1_cryland
	global.__objectDepths[283] = -19; // lvl2_cryland
	global.__objectDepths[284] = -19; // lvl3_cryland
	global.__objectDepths[285] = -19; // lvl4_cryland
	global.__objectDepths[286] = -19; // lvl5_cryland
	global.__objectDepths[287] = -19; // lvl6_cryland
	global.__objectDepths[288] = -19; // lvl7_cryland
	global.__objectDepths[289] = -19; // lvl8_cryland
	global.__objectDepths[290] = -19; // lvl9_cryland
	global.__objectDepths[291] = -19; // lvl10_cryland
	global.__objectDepths[292] = -19; // lvl11_cryland
	global.__objectDepths[293] = -19; // lvl12_cryland
	global.__objectDepths[294] = -19; // lvl13_cryland
	global.__objectDepths[295] = -19; // lvl14_cryland
	global.__objectDepths[296] = 0; // obj_flag


	global.__objectNames[0] = "obj_tiles";
	global.__objectNames[1] = "obj_endangered";
	global.__objectNames[2] = "obj_crystal";
	global.__objectNames[3] = "obj_waterlogged";
	global.__objectNames[4] = "obj_wavy";
	global.__objectNames[5] = "obj_muddy";
	global.__objectNames[6] = "obj_cursedstatue";
	global.__objectNames[7] = "obj_parent_mons";
	global.__objectNames[8] = "obj_seedy";
	global.__objectNames[9] = "obj_parent_plant";
	global.__objectNames[10] = "obj_projectile";
	global.__objectNames[11] = "obj_otherdame";
	global.__objectNames[12] = "obj_treeOfWishom";
	global.__objectNames[13] = "obj_sunflower";
	global.__objectNames[14] = "obj_peashooter";
	global.__objectNames[15] = "obj_icepea";
	global.__objectNames[16] = "obj_repeater";
	global.__objectNames[17] = "obj_wallnut";
	global.__objectNames[18] = "obj_potatobom";
	global.__objectNames[19] = "obj_cherrybom";
	global.__objectNames[20] = "obj_castuss";
	global.__objectNames[21] = "obj_iceletuce";
	global.__objectNames[22] = "obj_squash";
	global.__objectNames[23] = "obj_splitpea";
	global.__objectNames[24] = "obj_dragonfruit";
	global.__objectNames[25] = "obj_eggplant";
	global.__objectNames[26] = "obj_lilypad";
	global.__objectNames[27] = "obj_threepeater";
	global.__objectNames[28] = "obj_blover";
	global.__objectNames[29] = "obj_chomper";
	global.__objectNames[30] = "obj_bananaheart";
	global.__objectNames[31] = "obj_custarnade";
	global.__objectNames[32] = "obj_puffshroom";
	global.__objectNames[33] = "obj_sunshroom";
	global.__objectNames[34] = "obj_blasterflower";
	global.__objectNames[35] = "obj_lightflower";
	global.__objectNames[36] = "obj_sadshroom";
	global.__objectNames[37] = "obj_possonshroom";
	global.__objectNames[38] = "obj_doomshroom";
	global.__objectNames[39] = "obj_ca0";
	global.__objectNames[40] = "obj_ca1";
	global.__objectNames[41] = "obj_ca2";
	global.__objectNames[42] = "obj_ca3";
	global.__objectNames[43] = "obj_ca4";
	global.__objectNames[44] = "obj_ca5";
	global.__objectNames[45] = "obj_ca6";
	global.__objectNames[46] = "obj_ca7";
	global.__objectNames[47] = "obj_ca8";
	global.__objectNames[48] = "obj_ca9";
	global.__objectNames[49] = "obj_ca10";
	global.__objectNames[50] = "obj_ca11";
	global.__objectNames[51] = "obj_ca12";
	global.__objectNames[52] = "obj_ca13";
	global.__objectNames[53] = "obj_ca14";
	global.__objectNames[54] = "obj_ca15";
	global.__objectNames[55] = "obj_ca16";
	global.__objectNames[56] = "obj_ca17";
	global.__objectNames[57] = "obj_ca18";
	global.__objectNames[58] = "obj_ca19";
	global.__objectNames[59] = "obj_ca20";
	global.__objectNames[60] = "obj_ca21";
	global.__objectNames[61] = "obj_ca22";
	global.__objectNames[62] = "obj_ca23";
	global.__objectNames[63] = "obj_ca24";
	global.__objectNames[64] = "obj_ca25";
	global.__objectNames[65] = "obj_cshovel";
	global.__objectNames[66] = "obj_cpf";
	global.__objectNames[67] = "obj_monster";
	global.__objectNames[68] = "obj_brownie";
	global.__objectNames[69] = "obj_monsterdog";
	global.__objectNames[70] = "obj_hardcore";
	global.__objectNames[71] = "obj_imp";
	global.__objectNames[72] = "obj_gigantic";
	global.__objectNames[73] = "obj_blackdog";
	global.__objectNames[74] = "obj_scorpion";
	global.__objectNames[75] = "obj_sandstorm";
	global.__objectNames[76] = "obj_driller";
	global.__objectNames[77] = "obj_rex";
	global.__objectNames[78] = "obj_scopiking";
	global.__objectNames[79] = "obj_desertSummoner";
	global.__objectNames[80] = "obj_dragonfly";
	global.__objectNames[81] = "obj_krockodile";
	global.__objectNames[82] = "obj_spider";
	global.__objectNames[83] = "obj_slime";
	global.__objectNames[84] = "obj_urusal";
	global.__objectNames[85] = "obj_swampSummer";
	global.__objectNames[86] = "obj_skelegon";
	global.__objectNames[87] = "obj_crystard";
	global.__objectNames[88] = "obj_eyebat";
	global.__objectNames[89] = "obj_helahula";
	global.__objectNames[90] = "obj_darkpatrol";
	global.__objectNames[91] = "obj_annabelle";
	global.__objectNames[92] = "obj_vollo";
	global.__objectNames[93] = "obj_crylandsummoner";
	global.__objectNames[94] = "obj_piercing";
	global.__objectNames[95] = "obj_plantfood";
	global.__objectNames[96] = "obj_sunny";
	global.__objectNames[97] = "obj_snowpea";
	global.__objectNames[98] = "obj_pea";
	global.__objectNames[99] = "obj_potatoboms";
	global.__objectNames[100] = "obj_impact";
	global.__objectNames[101] = "obj_bucxanhiet";
	global.__objectNames[102] = "obj_waving";
	global.__objectNames[103] = "obj_bucxanhiet2";
	global.__objectNames[104] = "obj_flash";
	global.__objectNames[105] = "obj_flash2";
	global.__objectNames[106] = "obj_shutdown";
	global.__objectNames[107] = "obj_skmna";
	global.__objectNames[108] = "obj_poisonous";
	global.__objectNames[109] = "obj_lawnmover";
	global.__objectNames[110] = "obj_venomshoot";
	global.__objectNames[111] = "obj_floorfire";
	global.__objectNames[112] = "obj_spiderweb";
	global.__objectNames[113] = "obj_bananabomb";
	global.__objectNames[114] = "obj_spore";
	global.__objectNames[115] = "obj_tounge";
	global.__objectNames[116] = "obj_poisonbomb";
	global.__objectNames[117] = "obj_diemkydi";
	global.__objectNames[118] = "obj_crystalbroke";
	global.__objectNames[119] = "obj_laserbeam";
	global.__objectNames[120] = "obj_pseudolight";
	global.__objectNames[121] = "obj_mysteriouswave";
	global.__objectNames[122] = "obj_possonspread";
	global.__objectNames[123] = "obj_possonblt";
	global.__objectNames[124] = "obj_possoncloud";
	global.__objectNames[125] = "obj_sporedest";
	global.__objectNames[126] = "obj_phonglon";
	global.__objectNames[127] = "obj_fireskull";
	global.__objectNames[128] = "obj_vtmp";
	global.__objectNames[129] = "obj_light";
	global.__objectNames[130] = "obj_smassh";
	global.__objectNames[131] = "director";
	global.__objectNames[132] = "obj_sunpoint";
	global.__objectNames[133] = "obj_hugewave";
	global.__objectNames[134] = "obj_finalwave";
	global.__objectNames[135] = "obj_pLants";
	global.__objectNames[136] = "obj_yoilost";
	global.__objectNames[137] = "obj_poisonexp";
	global.__objectNames[138] = "obj_greenTargeted";
	global.__objectNames[139] = "obj_purpleTargeted";
	global.__objectNames[140] = "obj_abouttoshoot";
	global.__objectNames[141] = "obj_poisonlaser";
	global.__objectNames[142] = "obj_lvlup";
	global.__objectNames[143] = "obj_apple";
	global.__objectNames[144] = "obj_bananadest";
	global.__objectNames[145] = "obj_gernadecap";
	global.__objectNames[146] = "obj_wormhair";
	global.__objectNames[147] = "obj_4by4des";
	global.__objectNames[148] = "obj_poisonbam";
	global.__objectNames[149] = "obj_muddyblast";
	global.__objectNames[150] = "obj_urusalhead";
	global.__objectNames[151] = "obj_skelegonCorpse";
	global.__objectNames[152] = "obj_annabelleCorpse";
	global.__objectNames[153] = "obj_centrelight";
	global.__objectNames[154] = "obj_lightpillar";
	global.__objectNames[155] = "obj_bamsummon";
	global.__objectNames[156] = "obj_fsexp";
	global.__objectNames[157] = "obj_boxmodel";
	global.__objectNames[158] = "obj_touchpoint";
	global.__objectNames[159] = "obj_lightlaunch";
	global.__objectNames[160] = "obj_lightdirect";
	global.__objectNames[161] = "obj_banbeam";
	global.__objectNames[162] = "obj_hiroshima";
	global.__objectNames[163] = "obj_crater";
	global.__objectNames[164] = "obj_soul";
	global.__objectNames[165] = "obj_vollohead";
	global.__objectNames[166] = "obj_hometown";
	global.__objectNames[167] = "obj_desert";
	global.__objectNames[168] = "obj_swamp";
	global.__objectNames[169] = "obj_cryland";
	global.__objectNames[170] = "obj_kangdynasty";
	global.__objectNames[171] = "obj_volcanic";
	global.__objectNames[172] = "obj_arenaofvalor";
	global.__objectNames[173] = "obj_letrock";
	global.__objectNames[174] = "obj_letrock2";
	global.__objectNames[175] = "obj_return";
	global.__objectNames[176] = "obj_getgo";
	global.__objectNames[177] = "obj_unlock";
	global.__objectNames[178] = "obj_drop1";
	global.__objectNames[179] = "obj_drop2";
	global.__objectNames[180] = "obj_drop3";
	global.__objectNames[181] = "obj_arrow";
	global.__objectNames[182] = "bufferer";
	global.__objectNames[183] = "levelsystem1";
	global.__objectNames[184] = "controller";
	global.__objectNames[185] = "obj_plantboard";
	global.__objectNames[186] = "obj_selectboard";
	global.__objectNames[187] = "obj_voyager";
	global.__objectNames[188] = "obj_line1";
	global.__objectNames[189] = "obj_line2";
	global.__objectNames[190] = "obj_line3";
	global.__objectNames[191] = "obj_line4";
	global.__objectNames[192] = "obj_line5";
	global.__objectNames[193] = "obj_white";
	global.__objectNames[194] = "obj_black";
	global.__objectNames[195] = "obj_spectator";
	global.__objectNames[196] = "obj_enemies";
	global.__objectNames[197] = "obj_PR";
	global.__objectNames[198] = "obj_lvl1_b";
	global.__objectNames[199] = "obj_lvl2_b";
	global.__objectNames[200] = "obj_lvl3_b";
	global.__objectNames[201] = "obj_lvl4_b";
	global.__objectNames[202] = "obj_lvl5_b";
	global.__objectNames[203] = "obj_lvl6_b";
	global.__objectNames[204] = "obj_lvl7_b";
	global.__objectNames[205] = "obj_lvl8_b";
	global.__objectNames[206] = "obj_lvl9_b";
	global.__objectNames[207] = "obj_lvl10_b";
	global.__objectNames[208] = "obj_lvl1_c";
	global.__objectNames[209] = "obj_lvl2_c";
	global.__objectNames[210] = "obj_lvl3_c";
	global.__objectNames[211] = "obj_lvl4_c";
	global.__objectNames[212] = "obj_lvl5_c";
	global.__objectNames[213] = "obj_lvl6_c";
	global.__objectNames[214] = "obj_lvl7_c";
	global.__objectNames[215] = "obj_lvl8_c";
	global.__objectNames[216] = "obj_lvl9_c";
	global.__objectNames[217] = "obj_lvl10_c";
	global.__objectNames[218] = "obj_lvl11_c";
	global.__objectNames[219] = "obj_lvl12_c";
	global.__objectNames[220] = "obj_lvl13_c";
	global.__objectNames[221] = "obj_lvl1_d";
	global.__objectNames[222] = "obj_lvl2_d";
	global.__objectNames[223] = "obj_lvl3_d";
	global.__objectNames[224] = "obj_lvl4_d";
	global.__objectNames[225] = "obj_lvl5_d";
	global.__objectNames[226] = "obj_lvl6_d";
	global.__objectNames[227] = "obj_lvl7_d";
	global.__objectNames[228] = "obj_lvl8_d";
	global.__objectNames[229] = "obj_lvl9_d";
	global.__objectNames[230] = "obj_lvl10_d";
	global.__objectNames[231] = "obj_lvl11_d";
	global.__objectNames[232] = "obj_lvl12_d";
	global.__objectNames[233] = "obj_lvl1_e";
	global.__objectNames[234] = "obj_lvl2_e";
	global.__objectNames[235] = "obj_lvl3_e";
	global.__objectNames[236] = "obj_lvl4_e";
	global.__objectNames[237] = "obj_lvl5_e";
	global.__objectNames[238] = "obj_lvl6_e";
	global.__objectNames[239] = "obj_lvl7_e";
	global.__objectNames[240] = "obj_lvl8_e";
	global.__objectNames[241] = "obj_lvl9_e";
	global.__objectNames[242] = "obj_lvl10_e";
	global.__objectNames[243] = "obj_lvl11_e";
	global.__objectNames[244] = "obj_lvl12_e";
	global.__objectNames[245] = "obj_lvl13_e";
	global.__objectNames[246] = "obj_lvl14_e";
	global.__objectNames[247] = "lvl1_hometown";
	global.__objectNames[248] = "lvl2_hometown";
	global.__objectNames[249] = "lvl3_hometown";
	global.__objectNames[250] = "lvl4_hometown";
	global.__objectNames[251] = "lvl5_hometown";
	global.__objectNames[252] = "lvl6_hometown";
	global.__objectNames[253] = "lvl7_hometown";
	global.__objectNames[254] = "lvl8_hometown";
	global.__objectNames[255] = "lvl9_hometown";
	global.__objectNames[256] = "lvl10_hometown";
	global.__objectNames[257] = "lvl1_desert";
	global.__objectNames[258] = "lvl2_desert";
	global.__objectNames[259] = "lvl3_desert";
	global.__objectNames[260] = "lvl4_desert";
	global.__objectNames[261] = "lvl5_desert";
	global.__objectNames[262] = "lvl6_desert";
	global.__objectNames[263] = "lvl7_desert";
	global.__objectNames[264] = "lvl8_desert";
	global.__objectNames[265] = "lvl9_desert";
	global.__objectNames[266] = "lvl10_desert";
	global.__objectNames[267] = "lvl11_desert";
	global.__objectNames[268] = "lvl12_desert";
	global.__objectNames[269] = "lvl13_desert";
	global.__objectNames[270] = "lvl1_swamp";
	global.__objectNames[271] = "lvl2_swamp";
	global.__objectNames[272] = "lvl3_swamp";
	global.__objectNames[273] = "lvl4_swamp";
	global.__objectNames[274] = "lvl5_swamp";
	global.__objectNames[275] = "lvl6_swamp";
	global.__objectNames[276] = "lvl7_swamp";
	global.__objectNames[277] = "lvl8_swamp";
	global.__objectNames[278] = "lvl9_swamp";
	global.__objectNames[279] = "lvl10_swamp";
	global.__objectNames[280] = "lvl11_swamp";
	global.__objectNames[281] = "lvl12_swamp";
	global.__objectNames[282] = "lvl1_cryland";
	global.__objectNames[283] = "lvl2_cryland";
	global.__objectNames[284] = "lvl3_cryland";
	global.__objectNames[285] = "lvl4_cryland";
	global.__objectNames[286] = "lvl5_cryland";
	global.__objectNames[287] = "lvl6_cryland";
	global.__objectNames[288] = "lvl7_cryland";
	global.__objectNames[289] = "lvl8_cryland";
	global.__objectNames[290] = "lvl9_cryland";
	global.__objectNames[291] = "lvl10_cryland";
	global.__objectNames[292] = "lvl11_cryland";
	global.__objectNames[293] = "lvl12_cryland";
	global.__objectNames[294] = "lvl13_cryland";
	global.__objectNames[295] = "lvl14_cryland";
	global.__objectNames[296] = "obj_flag";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
